#:schema node_modules/wrangler/config-schema.json
name = "buling-imgbed-backend"
main = "src/index.js"
compatibility_date = "2024-06-06"

[observability]
enabled = true

[[d1_databases]]
binding = "MY_DB"
database_name = "buling-imgbed-d1"
database_id = "xxxx"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "buling-imgbed-r2"


[vars]
JWT_SECRET = "随机uuid生成" 
TG_BOT_TOKEN = "TG机器人token"


 